# Лабораторная работа № 1.2 — Метод прогонки

Вариант 6. 

Матрица трёхдиагональна. На прямом ходе выражаем x_i=p_i x_(i+1)+q_i, на обратном восстанавливаем неизвестные с конца.

## Исходные данные

Числа ниже соответствуют файлу input.txt этой работы.

In [1]:
import math
import numpy as np
import matplotlib.pyplot as plt
from typing import List

rows = [[6.0, -5.0], [-6.0, 16.0, 9.0], [9.0, -17.0, -3.0], [8.0, 22.0, -8.0], [6.0, -13.0], [-58.0, 161.0, -114.0, -90.0, -55.0]]
compact, d = rows[:-1], rows[-1]
n = len(d)
A = [[0.0]*n for _ in range(n)]
for i, row in enumerate(compact):
    if i == 0:
        A[i][i], A[i][i+1] = row
    elif i == n-1:
        A[i][i-1], A[i][i] = row
    else:
        A[i][i-1], A[i][i], A[i][i+1] = row
print('A =\n', np.array(A), '\nd =', d)

A =
 [[  6.  -5.   0.   0.   0.]
 [ -6.  16.   9.   0.   0.]
 [  0.   9. -17.  -3.   0.]
 [  0.   0.   8.  22.  -8.]
 [  0.   0.   0.   6. -13.]] 
d = [-58.0, 161.0, -114.0, -90.0, -55.0]


## Прямой и обратный ход

Знаменатель на шаге i учитывает уже исключённое x_(i-1). Затем обратный ход начинается с последней строки.

In [2]:
def tridiagonal_matrix_algorithm(A, d):
    n = len(d)
    p = [0.0] * n
    q = [0.0] * n
    # Прямой ход: x_i = p_i*x_(i+1) + q_i.
    for i in range(n):
        a = A[i][i - 1] if i > 0 else 0.0
        c = A[i][i + 1] if i < n - 1 else 0.0
        denominator = A[i][i] + (a * p[i - 1] if i else 0.0)
        if denominator == 0:
            raise ValueError("Thomas algorithm encountered a zero denominator")
        p[i] = -c / denominator
        q[i] = (d[i] - (a * q[i - 1] if i else 0.0)) / denominator
    x = [0.0] * n
    for i in range(n - 1, -1, -1):
        x[i] = q[i] + (p[i] * x[i + 1] if i < n - 1 else 0.0)
    return x


def matrix_vector_mult(A, x):
    n = len(A)
    m = len(x)
    return [sum(A[i][k] * x[k] for k in range(m)) for i in range(n)]

In [3]:
x = tridiagonal_matrix_algorithm(A, d)
print('x =', np.round(x, 8))

x = [-8.  2.  9. -7.  1.]


## Самопроверка

Умножь исходную матрицу на найденный вектор.

In [4]:
residual = np.max(np.abs(np.array(matrix_vector_mult(A, x))-d))
assert residual < 1e-10
print('Невязка ||Ax-d||∞ =', residual)

Невязка ||Ax-d||∞ = 0.0
